project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^artist_list/$', 'app.views.artist_list'),
    url(r'^artist_detail/(?P<pk>.+)/$', 'app.views.artist_detail'),

    url(r'^album_list/$', 'app.views.album_list'),
    url(r'^album_detail/(?P<pk>.+)/$', 'app.views.album_detail'),

    url(r'^signup/$', 'app.views.sign_up'),
    url(r'^logout/$', 'app.views.logout_view'),
    url(r'^signin/$', 'app.views.login_view'),
    url(r'^create_album/$', 'app.views.create_album'),
    url(r'^edit_album/(?P<pk>.+)/$', 'app.views.edit_album'),

    url(r'^delete_album/(?P<pk>.+)/$', 'app.views.delete_album'),

    url(r'^profile/$', 'app.views.profile_page'),
    url(r'^edit_profile/$', 'app.views.edit_profile'),
    url(r'^fav_artist/(?P<pk>.+)/$', 'app.views.fav_artist'),
    url(r'^unfav_artist/(?P<pk>.+)/$', 'app.views.unfav_artist'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from django.utils import timezone
from django.utils.http import urlquote
from django.core.mail import send_mail

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# Create your models here.
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()

        if not email:
            raise ValueError('Email must be set')

        email = self.normalize_email(email)

        user = self.model(email=email,
                          is_staff=is_staff,
                          is_active=True,
                          is_superuser=is_superuser,
                          last_login=now,
                          date_joined=now,
                          **extra_fields
                        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', max_length=255, unique=True)
    first_name = models.CharField('first name', max_length=255, blank=True, null=True)
    last_name = models.CharField('last name', max_length=255, blank=True, null=True)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=False)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)
    objects = CustomUserManager()

    fav_artists = models.ManyToManyField('app.Artist')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __unicode__(self):
        return self.email

    def get_absolute_url(self):
        return '/users/%s' % urlquote(self.email)

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        send_mail(subject,message,from_email, [self.email])


class Genre(models.Model):
    genre_id = models.IntegerField(null=True, blank=True)
    genre_parent_id = models.IntegerField(null=True, blank=True)
    genre_title = models.CharField(null=True, blank=True, max_length=255)
    genre_handle = models.SlugField(null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.genre_title

class Artist(models.Model):
    artist_id = models.IntegerField(null=True, blank=True)
    artist_handle = models.CharField(null=True, blank=True, max_length=255)
    artist_name  = models.CharField(null=True, blank=True, max_length=255)
    artist_url = models.URLField(null=True, blank=True)
    artist_image = models.ImageField(null=True, blank=True, upload_to='artist_images')

    def __unicode__(self):
        return '%s' % self.artist_name

class Album(models.Model):
    album_id = models.IntegerField(null=True, blank=True)
    album_title = models.CharField(null=True, blank=True, max_length=255)
    artist_name = models.CharField(null=True, blank=True, max_length=255)
    album_image = models.ImageField(null=True, blank=True, upload_to='album_images')
    artist = models.ForeignKey('app.Artist', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.album_title

class Track(models.Model):
    track_id = models.IntegerField(null=True, blank=True)
    track_title = models.CharField(null=True, blank=True, max_length=255)
    track_url = models.URLField(null=True, blank=True)
    track_image_file = models.ImageField(null=True, blank=True, upload_to='track_images')
    artist_id = models.IntegerField(null=True, blank=True)
    album_id = models.IntegerField(null=True, blank=True)

app/templates/album_list.html
{% for album in albums %}
	<a href="/album_detail/{{ album.pk }}/">{{ album.album_title }}</a><br>
{% endfor %}

app/templates/artist_detail.html
{% if request.user.is_authenticated %}
	<a href="/logout/">logout</a>
{% else %}
	<a href="/signin/">signin</a>
{% endif %}
<br>

{{ artist.artist_id}}<br>
{{ artist.artist_handle }}<br>
{{ artist.artist_name }}<br>
{{ artist.artist_url }}<br>

<h3>Albums</h3>
{% if request.user.is_superuser %}
<a href="/create_album/">create</a>
<br>
{% endif %}
{% for album in artist.album_set.all %}

	{% if request.user.is_superuser %}
		{{ album.album_title }}
		<a href="/edit_album/{{ album.pk }}">| edit |</a>
		<a href="/delete_album/{{ album.pk }}">| delete |</a>
		<br>
	{% else %}
		{{ album.album_title }}
		<br>
	{% endif %}
	
{% endfor %}

app/templates/artist_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
	<div class="row">
{% for artist in artists %}

		{% if artist %}
		<div class="col-md-3">
			<a href="/artist_detail/{{ artist.pk }}/">
				{{ artist.artist_name }}
			</a> 

			{% if artist not in request.user.fav_artists.all %}
				<a href="/fav_artist/{{ artist.pk }}/">
					+
				</a>
			{% else %}
				<a href="/unfav_artist/{{ artist.pk }}/">
					-
				</a>
			{% endif %}


		</div>
		{% endif %}

{% endfor %}
	</div>
</div>

{% endblock %}

app/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Music App</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if request.user.is_authenticated %}
                <li><a href="/logout/">Logout</a></li>
            {% else %}
                <li><a href="/signin/">Sign In</a></li>
            {% endif %}

            {% if request.user.is_authenticated %}
                <li><a href="/profile/">Profile</a></li>            
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
      </div>
    </div>

    {% block body %}
    {% endblock %}  
        
        <script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>

        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->

    </body>
</html>

app/templates/create_album.html
{% extends 'base.html' %}


{% block body %}

<form action='/create_album/' method='POST'>
	{% csrf_token %}
	{{ form.as_p }}
	<input type='submit' value='Create'>
</form>

{% endblock %}

app/templates/edit_album.html
{% extends 'base.html' %}


{% block body %}

	<form action='/edit_album/{{ album.pk }}/' method='POST'>

		{% csrf_token %}
			
		{{ form.as_p }}

	<input type='submit' value='Save' />

	</form>

{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block body %}

<form action='/edit_profile/' method='POST'>
	{% csrf_token %}
	{{ form.as_p }}

	<input type='submit' value='Save'>
</form>

{% endblock %}

app/templates/profile_page.html
{% extends 'base.html' %}

{% block body %}

	<p>Email: {{ user.email }}</p>
	<p>First Name: {{ user.first_name }}</p>
	<p>Last Name: {{ user.last_name }}</p>
	<p>Date Joined: {{ user.date_joined }}</p>


	<a href="/edit_profile/">Edit Profile</a>

	<br>
	<h3>Favorite Artists</h3>

	{% for fav in user.fav_artists.all %}

		<a href="/artist_detail/{{ fav.pk }}/">{{ fav.artist_name }}</a>
		<a href="/unfav_artist/{{ fav.pk}}/"> - </a>

		<br>

	{% endfor %}

{% endblock %}

app/templates/signin.html
{% extends 'base.html' %}

{% block body %}
	
	{% if request.user.is_authenticated %}
	Welcome: {{ request.user }}<br>
	<a href="/logout/">logout</a>
	{% endif %}

	

	{% if not request.user.is_authenticated %}
		<form action='/signin/' method='POST'>
			{% csrf_token %}
			{{ form.as_p }}
			<input type='submit' value='Sign In' />
		</form>
	{% endif %}

{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block body %}


	<div class="container">
		{% if request.user.is_authenticated %}
		<div class="row">
			<div class="col-md-12">
				Welcome : {{ request.user}}<br>
				<a href="/logout/">logout</a>
			</div>
		</div>
		{% endif %}

		{% if not request.user.is_authenticated %}
		<div class="row">
			<div class="col-md-12">
				<form action='/signup/' method='POST'>
					{% csrf_token %}
					{{ form.as_p }}
					<input type='submit' value='Sign Up'>
				</form>
			</div>
		</div>
		{% endif %}
	</div>

{% endblock %}